export type Deal = {
  itemId: string;
  title: string;
  itemWebUrl: string;
  price: { value: string; currency: string };
  image: { imageUrl: string };
  additionalImages: { imageUrl: string }[];
  featured: boolean;
  category: string;
  cohort?: "genz" | "millennial" | "og" | string;
  kind?: string;
  originalPrice?: number;
  discountPercent?: number;
  soldAvg?: number;
  condition?: string;
  authenticityGuarantee?: boolean;
  family?: string;
  apparel?: string;
  denimBrand?: string;
  collectibleKind?: string;
  watchTier?: string;
};

export type ListingRow = {
  title: string;
  category?: string;
  item_type?: string;
  original_price?: number | string;
  sale_price?: number | string;
  discount_percent?: number | string;
  affiliate_url?: string;
  image_url?: string;
  source_platform?: string;
  currency?: string;
  family?: string;
  apparel?: string;
  denim_brand?: string;
  collectible_kind?: string;
  tier?: string;
  sneakers?: { family?: string };
  streetwear?: { apparel?: string };
  collectibles?: { kind?: string };
  watches?: { tier?: string };
};

export type CohortRow = {
  ebay_id: string;
  title: string;
  model?: string | null;
  kind?: string | null;
  category?: string | null;
  price?: number | string | null;
  sold_avg?: number | string | null;
  discount_pct?: number | string | null;
  image_url?: string | null;
  product_url?: string | null;
  affiliate_url?: string | null;
  authenticity_guarantee?: boolean | null;
  ended?: boolean | null;
  cohort?: string | null;
  condition?: string | null;
  featured?: boolean | null;
  hero_role?: string | null;
  family?: string | null;
  apparel?: string | null;
  denim_brand?: string | null;
  collectible_kind?: string | null;
  tier?: string | null;
};
